#Note: this file only affects the local project makefile
#GENERAL
#COMPILE_PLATFORMS=(LINUX ANDROID WEB)


#PROJECT_VARIABLES
#PROJECT_NAME="Zed Example"
#PROJECT_VERSION="1.0"
#PROJECT_BUILD_PATH=build
#PROJECT_SOURCE_FILES
#GAME_RESOURCE_DIR


#DESKTOP
TARGET_BACKEND=BACKEND_RGFW
#TARGET_OPENGL_VERSION=3.3
#PLATFORM_NAME=desktop

#GLFW_USE_EXTERNAL=FALSE
#GLFW_INCLUDE_PATH=$(RAYLIB_PLATFORM_PATH)/external/GLFW/include
#GLFW_LIBRARY_PATH=$(RAYLIB_PLATFORM_PATH)/external/GLFW/lib
# GLFW_LINUX_DISPLAY_PROTOCOL=X11 OR WAYLAND
#GLFW_LINUX_ENABLE_WAYLAND=FALSE
#GLFW_LINUX_ENABLE_X11=TRUE

#SDL_INCLUDE_PATH      ?= $(RAYLIB_PLATFORM_PATH)/external/SDL2/include
#SDL_LIBRARY_PATH      ?= $(RAYLIB_PLATFORM_PATH)/external/SDL2/lib
#SDL_LIBRARIES         ?= -lSDL2 -lSDL2main

#RGFW_INCLUDE_PATH      ?= $(RAYLIB_PLATFORM_PATH)/external/RGFW/include
#RGFW_LIBRARIES         ?= -lRGFW


#WEB
#BUILD_WEB_ASYNCIFY    ?= FALSE
#BUILD_WEB_SHELL       ?= raylib/src/minshell.html
#BUILD_WEB_HEAP_SIZE   ?= 128MB
#BUILD_WEB_STACK_SIZE  ?= 1MB
#BUILD_WEB_ASYNCIFY_STACK_SIZE ?= 1048576
#BUILD_WEB_RESOURCES   ?= FALSE
#BUILD_WEB_RESOURCES_PATH  ?= resources
EMSCRIPTEN_USE_GIT=TRUE
#EMSCRIPTEN_GIT_PATH      ?= $(RAYLIB_PLATFORM_PATH)/external/emscripten

#ANDROID
#ANDROID_NDK_VERSION=r29
#ANDROID_SDK_VERSION=
